apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: VeleroBackup
metadata:
  labels:
    app.kubernetes.io/name: velerobackup
    app.kubernetes.io/instance: azbackup-sample
    app.kubernetes.io/part-of: cluster-api-addon-provider-velero
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-addon-provider-velero
  name: azbackup-sample
  namespace: creategitops-me7ee7
spec:
  installation:
    ref:
      kind: VeleroInstallation
      name: sample-az
      namespace: creategitops-me7ee7