---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - helmchartproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - helmchartproxies/finalizers
  verbs:
  - update
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - helmchartproxies/status
  verbs:
  - get
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - velerobackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - velerobackups/finalizers
  verbs:
  - update
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - velerobackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - veleroinstallations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - veleroinstallations/finalizers
  verbs:
  - update
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - veleroinstallations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - velerorestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - velerorestores/finalizers
  verbs:
  - update
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - velerorestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - veleroschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - veleroschedules/finalizers
  verbs:
  - update
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - veleroschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters/status
  verbs:
  - get
