# permissions for end users to edit velerorestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: velerorestore-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-addon-provider-velero
    app.kubernetes.io/part-of: cluster-api-addon-provider-velero
    app.kubernetes.io/managed-by: kustomize
  name: velerorestore-editor-role
rules:
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - velerorestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - velerorestores/status
  verbs:
  - get
